backend:
  name: git-gateway #test-repo to test
  branch: cms-demo # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections:
  - name: "pages"
    label: "Pages"
    create: true
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Tags'
          name: "tags"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}